FROM node:18-alpine AS build-stage
WORKDIR /app

COPY src/frontend/package*.json ./
RUN npm install

COPY src/frontend ./
RUN npm run build

FROM nginx:stable-alpine
ENV ENVIRONMENT=prod

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
